<?xml version="1.0" encoding="utf-8"?><Database Name="ERBook" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=ERBook;Integrated Security=True" SettingsObjectName="CourseProject.Properties.Settings" SettingsPropertyName="ERBookConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Students" Member="Students">
    <Type Name="Students">
      <Column Name="id_student" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="group_st" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="patronymic" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Teachers" Member="Teachers">
    <Type Name="Teachers">
      <Column Name="id_teacher" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="subject" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="patronymic" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RegisterBook" Member="RegisterBook">
    <Type Name="RegisterBook">
      <Column Name="id_rb" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="class_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="topic" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="mark" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="id_teacher" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_student" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>